frases_felizes = [
    "um mundo vibrante de cores e alegria",
    "um oásis de tranquilidade e beleza esplêndida",
    "um paraíso cintilante com céus sempre azuis",
    "um arquipélago de ilhas radiantes e mares cristalinos",
    "um jardim celestial repleto de flores exuberantes e perfumadas",
    "uma utopia de harmonia, onde a felicidade ecoa em cada vale",
    "um céu dançante de auroras mágicas e estrelas cintilantes",
    "um reino de praias douradas e águas termais relaxantes",
    "um continente de festivais vibrantes e música contagiante",
    "um santuário de paz, com montanhas serenas e lagos tranquilos",
    "um vale de arco-íris e cachoeiras de água cristalina",
    "um campo de neve cintilante sob o brilho do sol eterno",
    "um oceano de possibilidades, repleto de aventuras e descobertas",
    "um sistema de cavernas místicas iluminadas por cristais luminosos",
    "um planeta de primaveras eternas, com flores desabrochando o ano todo",
    "um mundo de sonhos realizados, onde cada amanhecer traz novas esperanças",
    "um horizonte infinito de dunas douradas sob um céu estrelado",
    "um conjunto de ilhas flutuantes no céu, ligadas por pontes de nuvens",
    "um amanhecer deslumbrante, pintando o céu com cores vibrantes",
    "um bosque encantado, onde a magia e a natureza dançam juntas",
    "uma cidade de luzes brilhantes, onde cada rua irradia alegria",
    "um festival de balões coloridos, adornando o céu em celebração",
    "um jardim de borboletas cintilantes, voando livremente sob o sol",
    "um rio de estrelas cadentes, trazendo esperança a cada desejo feito",
    "um campo de tulipas multicoloridas, balançando ao sopro da brisa",
    "um palácio de cristal, refletindo a luz em mil arco-íris",
    "um carrossel de sonhos, girando em um mundo de maravilhas",
    "uma cascata de luzes auroras, dançando no céu noturno"
]

frases_tristes = [
    "um planeta sombrio, envolto em sombras eternas",
    "um mundo solitário, perdido nas profundezas frias do espaço",
    "uma esfera silenciosa, coberta por nuvens cinzentas e pesadas",
    "um deserto de gelo inóspito, onde o vento uiva tristezas esquecidas",
    "um mar de neblina, onde ecos de vozes perdidas vagam sem destino",
    "um pântano de silêncio, onde a vida se esconde nas sombras",
    "um labirinto de ruínas antigas, ecoando a desolação de eras passadas",
    "um vale de ossos ressecados, vestígios de um passado esquecido",
    "um abismo sem fim, engolindo toda luz e esperança",
    "uma terra devastada, marcada pelas cicatrizes de guerras antigas",
    "um campo de cinzas, onde a vida uma vez floresceu e agora jaz",
    "um mundo de escuridão perpétua, onde o sol nunca brilha",
    "um oceano de lágrimas congeladas, testemunha de incontáveis tristezas",
    "um planalto árido, onde o vento carrega sussurros de desespero",
    "um reino de névoa e frio, onde a alegria nunca visitou",
    "uma cidade fantasma, suas ruas e casas abandonadas ao tempo",
    "uma floresta de árvores mortas, onde não se ouve mais o canto dos pássaros",
    "um lago de reflexos distorcidos, espelho de uma realidade sombria",
    "um céu eternamente cinzento, sem esperança de um novo amanhecer",
    "um caminho coberto de folhas secas, sinalizando o fim do outono",
    "uma casa abandonada, ecoando as memórias de dias mais felizes",
    "um rio seco, leito de promessas esquecidas e sonhos desfeitos",
    "um castelo em ruínas, testemunha silenciosa de uma glória passada",
    "uma estrada deserta, estendendo-se para um horizonte vazio",
    "um parque de diversões vazio, onde risos já não ecoam",
    "um relógio parado, simbolizando momentos que nunca retornarão",
    "uma praia deserta ao anoitecer, onde as ondas murmuram segredos tristes",
    "um jardim de outono, onde as flores murcham sob um céu nublado"
]


frases_bravas = [
    "um terreno tempestuoso, com vulcões furiosos",
    "um deserto ardente, varrido por ventos implacáveis",
    "um reino de gelo quebradiço, onde tempestades de neve rugem incessantemente",
    "uma selva densa e impenetrável, repleta de feras selvagens e perigos ocultos",
    "um oceano turbulento, com ondas gigantes e tempestades devastadoras",
    "montanhas escarpadas, lar de trovões retumbantes e relâmpagos violentos",
    "um planeta de tempestades elétricas constantes, iluminando os céus com fúria",
    "um campo de batalha eterno, onde o som de armas nunca cessa",
    "uma terra de vulcões em erupção, cuspidores de fogo e cinzas",
    "um abismo de fúria e tormento, onde a serenidade é uma lembrança distante",
    "um deserto de lava ardente, fluindo com a ira de mil sóis",
    "uma cadeia de montanhas inóspitas, onde ventos cortantes sibilam com violência",
    "um planeta de tempestades de areia vorazes, que engolem tudo em seu caminho",
    "um mundo de rios ferventes e cachoeiras de fogo",
    "uma terra de terremotos e abalos, onde o solo nunca descansa",
    "um vale de trovoadas intermináveis, onde o som do trovão é a única música",
    "um planalto de pedras afiadas, cortantes como a raiva indomável",
    "um mar de ondas revoltas, quebrando-se com fúria contra rochas implacáveis",
    "um céu carregado de nuvens tempestuosas, prontas para desabar em fúria",
    "uma floresta em chamas, consumida pelo fogo da ira incontrolável",
    "um rio caudaloso, transbordando com a força de uma fúria indomável",
    "um vulcão prestes a explodir, refletindo a tensão e a ira acumulada",
    "um tornado selvagem, arrasando tudo com sua poderosa fúria",
    "um mar agitado durante uma tempestade feroz, espumando de raiva",
    "um campo elétrico pulsante, vibrando com energia intensa e indomável",
    "uma tempestade de granizo, caindo impiedosamente sobre a terra",
    "um furacão devastador, girando com uma fúria desenfreada",
    "uma avalanche imparável, descendo a montanha com uma força avassaladora"
]


frases_ambiguas = [
    "um caminho coberto de névoa, que pode levar a um destino deslumbrante ou a um beco sem saída",
    "um rio que flui suavemente, ocultando correntezas perigosas ou levando a águas tranquilas",
    "uma floresta densa, escondendo mistérios antigos ou promessas de descobertas maravilhosas",
    "uma cidade iluminada, vibrante de vida ou ecoando de solidão",
    "um castelo antigo, guardando tesouros esquecidos ou segredos sombrios",
    "uma estrada bifurcada, conduzindo a aventuras inesperadas ou a destinos desconhecidos",
    "um livro antigo, repleto de sabedoria profunda ou de histórias confusas",
    "uma porta misteriosa, abrindo para maravilhas ocultas ou para caminhos obscuros",
    "uma ponte sobre um abismo, oferecendo uma travessia segura ou um caminho incerto",
    "um espelho antigo, refletindo verdades ocultas ou ilusões enganosas",
    "um jardim secreto, um refúgio de paz ou um labirinto sem saída",
    "uma tempestade no horizonte, prometendo renovação ou trazendo destruição",
    "um relógio antigo, contando o tempo de momentos alegres ou de horas perdidas",
    "uma chave enferrujada, abrindo portas para tesouros ou para segredos perigosos",
    "um farol na costa, guiando para um porto seguro ou para rochas traiçoeiras",
    "um caminho coberto de folhas, levando a um refúgio tranquilo ou a um território desconhecido",
    "um navio à deriva, carregando sonhos de liberdade ou de exílio eterno",
    "uma caverna escondida, abrigando maravilhas naturais ou perigos ocultos",
    "um céu estrelado, sinalizando um futuro brilhante ou caminhos incertos",
    "uma estrada coberta de neve, convidando à aventura ou ao isolamento",
    "um labirinto de espelhos, refletindo inúmeras possibilidades ou confundindo a realidade",
    "uma biblioteca antiga, repleta de conhecimento ilimitado ou de enigmas indecifráveis",
    "uma colina com vista para a cidade, oferecendo perspectivas amplas ou isolamento",
    "um mercado agitado, prometendo descobertas empolgantes ou caos incontrolável",
    "uma mansão enigmática, cheia de histórias fascinantes ou segredos perturbadores",
    "uma praia ao entardecer, simbolizando tranquilidade ou a transitoriedade da vida",
    "um carrossel parado, evocando alegrias da infância ou o passar do tempo",
    "um relógio de sol antigo, medindo momentos preciosos ou lembrando a brevidade da vida"
]
